### DISCUSSION TITLE
NVIDIA GTX 550 ti ===>> GPU not found

### DISCUSSION THREAD

**Discussion by rtdietrich** [bevyengine/bevy#12798] [Q&A]
When I run your example code , I get the message that my GPU is not found. I suspect that there is a connection because this GPU no longer supports Vulkan due to its age.
Is there a possibility to help me. I once heard that WGPU supports a compatibility mode. Is there something for bevy?

**Comment by BD103** [comment]
Hello! You are probably looking for #12542, which should fix your issue. It will be released in Bevy 0.13.2.

For now, you can depend on the unstable 0.13.2 branch. Add this to your `Cargo.toml`:

```toml
[patch.crates-io]
bevy = { git = "https://github.com/bevyengine/bevy", branch = "release-0.13.2" }
bevy_app = { git = "https://github.com/bevyengine/bevy", branch = "release-0.13.2" }
bevy_asset = { git = "https://github.com/bevyengine/bevy", branch = "release-0.13.2" }
bevy_ecs = { git = "https://github.com/bevyengine/bevy", branch = "release-0.13.2" }
# ...
```

You may find [this discussion on Discord](https://discord.com/channels/691052431525675048/692572690833473578/1224480460990845000) useful. Feel free to ask in the `#help` channel for more assistance. :)
