### DISCUSSION TITLE
Requested resource bevy_asset::server::AssetServer does not exist in the `World`.

### DISCUSSION THREAD

**Discussion by midstreeeam** [bevyengine/bevy#14105] [Q&A] [answered]
I tried to run a minimal bevy app with render plugin inited, but it gives `Requested resource bevy_asset::server::AssetServer does not exist in the World.`

My code: 
```rust
use bevy::prelude::*;

fn main() {
    App::new()
        .add_plugins((
            MinimalPlugins,
            bevy::render::RenderPlugin::default(),
        ))
        .run();
}
```

my cargo.toml:
```toml
[package]
name = "bevy_terminal"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = {version = "0.13.2", default-features = false, features = [
    "bevy_render",
]}
```

the error: 
```
thread 'main' panicked at /home/codespace/.cargo/registry/src/index.crates.io-6f17d22bba15001f/bevy_asset-0.13.2/src/lib.rs:370:20:
Requested resource bevy_asset::server::AssetServer does not exist in the `World`.
                Did you forget to add it using `app.insert_resource` / `app.init_resource`?
                Resources are also implicitly added via `app.add_event`,
                and can be added by plugins.
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

Adding bevy assets plugin does not solve the problem. Does any one know why this error msg is shown?
