### DISCUSSION TITLE
Reeling in no_std and no_web virality

### DISCUSSION THREAD

**Discussion by cart** [bevyengine/bevy#18799] [Ideas]
Bevy increasingly has "no std" (supports platforms that don't have an `std` impl) and "no web" (supports wasm builds that don't have access to the full web). This is really cool!

However I think the "virality" of both `std` and `web` features (and the proliferation of them in our codebase) is a maintenance liability and an "ecosystem UX" liability. Writing a new crate that supports these platforms requires intimate knowledge of the patterns we use to support them, what Bevy crates currently support them, and how to wire everything up to ensure you enable these features in the relevant crates.

Things like this are now everywhere in our codebase:

```toml
bevy_animation = { path = "../bevy_animation", version = "0.16.0-dev", optional = true }
bevy_app = { path = "../bevy_app", version = "0.16.0-dev" }
bevy_asset = { path = "../bevy_asset", version = "0.16.0-dev" }
bevy_color = { path = "../bevy_color", version = "0.16.0-dev" }
bevy_core_pipeline = { path = "../bevy_core_pipeline", version = "0.16.0-dev" }
bevy_ecs = { path = "../bevy_ecs", version = "0.16.0-dev" }
bevy_image = { path = "../bevy_image", version = "0.16.0-dev" }
bevy_math = { path = "../bevy_math", version = "0.16.0-dev" }
bevy_mesh = { path = "../bevy_mesh", version = "0.16.0-dev" }
bevy_pbr = { path = "../bevy_pbr", version = "0.16.0-dev" }
bevy_reflect = { path = "../bevy_reflect", version = "0.16.0-dev" }
bevy_render = { path = "../bevy_render", version = "0.16.0-dev" }
bevy_scene = { path = "../bevy_scene", version = "0.16.0-dev", features = [
  "bevy_render",
] }
bevy_transform = { path = "../bevy_transform", version = "0.16.0-dev" }
bevy_tasks = { path = "../bevy_tasks", version = "0.16.0-dev" }
bevy_utils = { path = "../bevy_utils", version = "0.16.0-dev" }
bevy_platform_support = { path = "../bevy_platform_support", version = "0.16.0-dev", default-features = false, features = [
  "std",
  "serialize",
] }

[target.'cfg(target_arch = "wasm32")'.dependencies]
bevy_log = { path = "../bevy_log", version = "0.16.0-dev", default-features = false, features = [
  "web",
] }
bevy_app = { path = "../bevy_app", version = "0.16.0-dev", default-features = false, features = [
  "web",
] }
bevy_platform_support = { path = "../bevy_platform_support", version = "0.16.0-dev", default-features = false, features = [
  "web",
] }
bevy_reflect = { path = "../bevy_reflect", version = "0.16.0-dev", default-features = false, features = [
  "web",
] }
bevy_tasks = { path = "../bevy_tasks", version = "0.16.0-dev", default-features = false, features = [
  "web",
] }
```

Every time you add some `bevy_x` dependency (either official or 3rd party), you need to ask yourself:

1. Does this have no_std support? If yes, create a "std" feature in your crate, and ensure you enable `bevy_x/std` feature when that is enabled.
2. Does this have "no web" support? If yes, create a "web" feature in your crate and ensure you enable "bevy_x/web" when it is enabled.
3. Does my crate _assume_ web support? If yes, ensure you enable `bevy_x/web` when building for the `wasm32`  target.

Likewise having `#[cfg(feature = "std")]` and `#[cfg(feature = "web")]` everywhere significantly affects legibility and maintainability. 

I think the way these things are framed (optional, but "viral" cargo features) _is_ correct, but I think we should investigate scoping down _which_ crates needs to care about this (and in an ideal world, no crates need to care about this). If we had a single place that handled these platform specific concerns and provided _platform agnostic_ interfaces consumers can code to (as in, the code compiles regardless of no_std / web-ness), then that crate wouldn't need to explicitly worry about platform configuration at all. Instead, the _end user_ (or the `bevy` crate) could define the "web" / "std" features directly on that crate.

That way the interface could be this for crates that depend on "core" bevy crates :

```toml
[package]
name = "my_bevy_plugin"

[dependencies]
bevy_app = "0.16"
bevy_ecs = "0.16"
bevy_asset = "0.16"
```

Likewise consumers of "my_bevy_plugin" could just do

```toml
my_bevy_plugin = "1.0"
```

And then the top level app could do:

```toml
bevy_app = "0.16"
bevy_ecs = "0.16"
my_bevy_plugin = "1.0"
# bevy_platform_support defaults to "std" and "web", so this is no_std and no_web
bevy_platform_support = { version = "0.16",  default-features = false }
```

Or alternatively:

```toml
# bevy would default to "std" and "web"
bevy = "0.16"
my_bevy_plugin = "1.0"
```

Or 
```toml
# this is "std", but "no web"
bevy = { version = "0.16", default-features = false, features = ["std"] }
my_bevy_plugin = "1.0"
```

The downside here is that _all_ std and web functionality would need to live in `bevy_platform_support` (risking compile time bottlenecking), and we'd need to ensure that we expose platform agnostic interfaces. This is a technical challenge, but not necessarily insurmountable.

It also wouldn't necessarily need to be exhaustive. We could focus on the low hanging fruit and piecemeal port things over to that paradigm, which could reduce how "deep" the roots currently go.

To keep `bevy_platform_support` slim, we could feature gate what it provides (ex: a "log" feature, a "collections" feature, etc).

I'll note that pretty much every platform-agnostic app framework builds interfaces like this (and we already use this approach in plenty of places, we're just overly leaky atm) . 

In practice, this would result in writing some APIs that do nothing on some platforms, adding runtime `if bevy_platform_support::IS_WEB { }` checks (which would be const), etc.
