### DISCUSSION TITLE
A solution to the `release.yml` workflow problem

### DISCUSSION THREAD

**Discussion by tguichaoua** [bevyengine/bevy#9432] [Ideas]
(cc: @cart)
I saw in #9080 that when a PR is created by a workflow the CI are not executed.
I got the same issue and found a solution [on stackoverflow](https://stackoverflow.com/a/72451611/11747494).

The problem is due to github tring to avoid recursive workflow runs.

The solution is to pass a [Personal Access Token (PAT)](https://docs.github.com/en/github/authenticating-to-github/creating-a-personal-access-token) with the scope `repo` to `peter-evans/create-pull-request`.
```yml
      - name: Create PR
        uses: peter-evans/create-pull-request@v5
        with:
          delete-branch: true
          base: "main"
          title: "Preparing Next Release"
          body: |
            Preparing next release
            This PR has been auto-generated
          token: ${{ secrets.PAT }}
```
