### DISCUSSION TITLE
Problem with using a local fork of Bevy

### DISCUSSION THREAD

**Discussion by floppyhammer** [bevyengine/bevy#9869] [Q&A] [answered]
## Bevy version

0.11.2

## What you did

I'm using Bevy to make some. I'm also using some crates which depend on Bevy (e.g. bevy_xpbd, bevy-inspector-egui). For some reason I need to switch from the official Bevy crate to a local repo. That's when issues happen.

## What went wrong

See https://github.com/Jondolf/bevy_xpbd/issues/157 for details.

## Additional information

None.

**Comment by mockersf** [comment]
How did you switch? To which version? Are you defining a direct dependency or a patch?

**Comment by floppyhammer** [comment]
I changed `bevy = "0.11.2"` to `bevy = { path = "../bevy" }` in `Cargo.toml`. The local Bevy repo is on the `0.11.2` branch.

**Comment by mockersf** [comment]
You should not change your dependency, and instead add a patch section:
```toml
[patch.crates-io]
bevy = { path = "../bevy" }
```
See https://doc.rust-lang.org/cargo/reference/overriding-dependencies.html#the-patch-section

If you change just your dependency, it will only change the version of Bevy in your own project. This will also change it in all your dependencies that use Bevy

**Comment by floppyhammer** [comment]
I did as you suggested. The compile error about "component" is gone, and I can build it with bevy_xpbd succesfully. However, if I use bevy_inspector_egui, another issue happens:

```
error[E0277]: the trait bound `EguiUserTextures: bevy_ecs::system::Resource` is not satisfied
   --> C:\Users\chy\.cargo\registry\src\index.crates.io-6f17d22bba15001f\bevy-inspector-egui-0.19.0\src\inspector_egui_impls\image.rs:44:45
    |
44  |         match world.get_two_resources_mut::<bevy_egui::EguiUserTextures, Assets<Image>>() {
    |                                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^ the trait `bevy_ecs::system::Resource` is not implemented for `EguiUserTextures`
```

But `Resource` is implemented for this structure.

```rust
/// A resource for storing `bevy_egui` user textures.
#[derive(Clone, Resource, Default)]
pub struct EguiUserTextures {
    textures: HashMap<Handle<Image>, u64>,
    last_texture_id: u64,
}
```

**Reply by mockersf** [reply]
It will depend how the versions of `bevy_inspector_egui` / `bevy_egui` you are using are depending on `bevy`.

You can investigate using `cargo tree`

**Comment by alice-i-cecile** [comment]
This is likely another "mismatched versions" problem unfortunately :/ The [Cheatbook] provides useful guidance here: https://bevy-cheatbook.github.io/setup/bevy-git.html?highlight=bleed#should-you-use-bleeding-edge-bevy

**Comment by nicopap** [comment, marked as answer]
you need to explicitly override every bevy crates.

Make sure to add `bevy_ecs`, `bevy_app` etc… all bevy crates to your `patch.crates-io` section. This is why I'd recommend 3rd party crate author to depend only explicitly on `bevy` and not the subcrates…

```toml
[patch.crates-io]
bevy = { path = "path/to/local/bevy" }
bevy_app = { path = "path/to/local/bevy/crates/bevy_app" }
bevy_asset = { path = "path/to/local/bevy/crates/bevy_asset" }
bevy_core = { path = "path/to/local/bevy/crates/bevy_core" }
bevy_ecs = { path = "path/to/local/bevy/crates/bevy_ecs" }
bevy_hierarchy = { path = "path/to/local/bevy/crates/bevy_hierarchy" }
bevy_log = { path = "path/to/local/bevy/crates/bevy_log" }
bevy_math = { path = "path/to/local/bevy/crates/bevy_math" }
bevy_reflect = { path = "path/to/local/bevy/crates/bevy_reflect" }
bevy_utils = { path = "path/to/local/bevy/crates/bevy_utils" }
bevy_window = { path = "path/to/local/bevy/crates/bevy_window" }
bevy_mikktspace = { path = "path/to/local/bevy/crates/bevy_mikktspace" }
bevy_transform = { path = "path/to/local/bevy/crates/bevy_transform" }
bevy_render = { path = "path/to/local/bevy/crates/bevy_render" }
bevy_time = { path = "path/to/local/bevy/crates/bevy_time" }
bevy_core_pipeline = { path = "path/to/local/bevy/crates/bevy_core_pipeline" }
bevy_pbr = { path = "path/to/local/bevy/crates/bevy_pbr" }
```
