### ISSUE TITLE
coreaudio-sys compile fails on MacOS due to LLVM change; cannot build bevy

### ISSUE THREAD

**Issue by dmlary** [bevyengine/bevy#10274]
## Bevy version

HEAD of master branch (a830530be4398fb0832992e5b4baefc316d1f1d0)

## Relevant system information

MacOS Ventura 13.6.1, but more importantly LLVM v15.0.0 (system version for ventura).

## What you did

`cargo build`

## What went wrong

Cannot build bevy on MacOS.  Build fails on `coreaudio-sys` with the following output:
```txt
error: failed to run custom build command for `coreaudio-sys v0.2.11`

Caused by:
  process didn't exit successfully: `/Users/dmlary/src/bevy/vendor/bevy/target/debug/build/coreaudio-sys-88e19d2770556f5d/build-script-build` (exit status: 101)
  --- stdout
  cargo:rerun-if-env-changed=COREAUDIO_SDK_PATH
  cargo:rustc-link-lib=framework=AudioUnit
  cargo:rustc-link-lib=framework=CoreAudio
  cargo:rerun-if-env-changed=BINDGEN_EXTRA_CLANG_ARGS

  --- stderr
  thread 'main' panicked at /Users/dmlary/.cargo/registry/src/index.crates.io-6f17d22bba15001f/proc-macro2-1.0.58/src/fallback.rs:811:9:
  "enum_(unnamed_at_/Library/Developer/CommandLineTools/SDKs/MacOSX_sdk/usr/include/MacTypes_h_382_1)" is not a valid Ident
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
warning: build failed, waiting for other jobs to finish...
```

The key piece is `enum_(unnamed_at_/Library/Developer/CommandLineTools/SDKs/MacOSX_sdk/usr/include/MacTypes_h_382_1)" is not a valid Ident`.

This is happening because LLVM changed the output for unnamed types, as a result bindgen generates invalid code.  There's an [issue](https://github.com/rust-lang/rust-bindgen/issues/2488) describing the problem, and says it is resolved in bindgen v0.62.  coreaudio-sys v0.2.12 updates to bindgen v0.64 [^coreaudio].

[^coreaudio]: https://github.com/RustAudio/coreaudio-sys/pull/86

## Additional information
I've confirmed that coreaudio-sys v0.2.11 will not build stand-alone on my macos system.  This is after removing all additional LLVM installs, removing and reinstalling xcode & xcode command-line tools.

When I update to  coreaudio-sys v0.2.12 (commit ad6cac44), I am able to build the crate with a few warnings, but it works.

**Comment by dmlary** [comment]
Damnit, this was my cargo.lock

**Comment by FrankenApps** [comment]
I had the same issue and can confirm that running `cargo update --package coreaudio-rs` fixed the problem.

**Comment by currenthandle** [comment]
I can't get this to work.

I've run `cargo update --package coreaudio-rs` and `cargo update --package coreaudio-sys`. I've also tried deleting the`Cargo.lock` file.

right now my `Cargo.toml` is:
```toml
[package]
name = "globe-bevy"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = "0.12.0"
coreaudio-sys = "0.2.12"

# Enable a small amount of optimization in debug mode
[profile.dev]
opt-level = 1

# Enable high optimizations for dependencies (incl. Bevy), but not for our code:
[profile.dev.package."*"]
opt-level = 3
```

I've also tried `coreaudio-sys = "0.2.14"`

`cargo build` output:
```sh

   Compiling coreaudio-sys v0.2.14
error: failed to run custom build command for `coreaudio-sys v0.2.14`

Caused by:
  process didn't exit successfully: `/Users/casey/Dev/ezkl-work/globe-bevy/target/debug/build/coreaudio-sys-9a5602721b8610bb/build-script-build` (exit status: 101)
  --- stdout
  cargo:rerun-if-env-changed=COREAUDIO_SDK_PATH
  cargo:rustc-link-lib=framework=AudioUnit
  cargo:rustc-link-lib=framework=AudioToolbox
  cargo:rustc-link-lib=framework=CoreAudio
  cargo:rustc-link-lib=framework=OpenAL
  cargo:rustc-link-lib=framework=CoreMIDI
  cargo:rerun-if-env-changed=BINDGEN_EXTRA_CLANG_ARGS

  --- stderr
  thread 'main' panicked at /Users/casey/.cargo/registry/src/index.crates.io-6f17d22bba15001f/bindgen-0.69.1/lib.rs:620:31:
  Unable to find libclang: "the `libclang` shared library at /opt/homebrew/opt/llvm@15/lib/libclang.dylib could not be opened: dlopen(/opt/homebrew/opt/llvm@15/lib/libclang.dylib, 0x0005): tried: '/opt/homebrew/opt/llvm@15/lib/libclang.dylib' (mach-o file, but is an incompatible architecture (have 'arm64', need 'x86_64')), '/System/Volumes/Preboot/Cryptexes/OS/opt/homebrew/opt/llvm@15/lib/libclang.dylib' (no such file), '/opt/homebrew/opt/llvm@15/lib/libclang.dylib' (mach-o file, but is an incompatible architecture (have 'arm64', need 'x86_64')), '/opt/homebrew/Cellar/llvm@15/15.0.7/lib/libclang.dylib' (mach-o file, but is an incompatible architecture (have 'arm64', need 'x86_64')), '/System/Volumes/Preboot/Cryptexes/OS/opt/homebrew/Cellar/llvm@15/15.0.7/lib/libclang.dylib' (no such file), '/opt/homebrew/Cellar/llvm@15/15.0.7/lib/libclang.dylib' (mach-o file, but is an incompatible architecture (have 'arm64', need 'x86_64'))"
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
warning: build failed, waiting for other jobs to finish...
```

`rust-toolchain.toml`
```toml
[toolchain]
channel = "nightly"
components = ["rustfmt", "clippy"]
targets = ["aarch64-apple-darwin"]
```
