### ISSUE TITLE
horizontal text alignment

### ISSUE THREAD

**Issue by robtfm** [bevyengine/bevy#10343]
## Bevy version

main

## What you did

i'm trying to get horizontal text alignment via flexbox, and failing. this is what i want:
![image](https://github.com/bevyengine/bevy/assets/50659922/d8f94d20-258b-4e51-af2c-1ec902bd465c)

which i can get in css with 
```html
<!DOCTYPE html>
<html>

<head> 
    <link rel="stylesheet" href="buttons.css"> 
</head>
 
<body>
    <div class="screen">
        <div class="holder">
            <div class="button" style = "justify-content: flex-end;">text</div>
            <div class="button">text</div>
            <div class="button" style = "justify-content: flex-end;">text</div>
            <div class="button">text</div>
        </div>
        <div class="holder">
            <div class="button" style = "justify-content: flex-end;"><div>text</div></div>
            <div class="button"><div>text</div></div>
            <div class="button" style = "justify-content: flex-end;"><div>text</div></div>
            <div class="button"><div>text</div></div>
        </div>
    </div>
</body>
</html>
 ```
```css
.screen {
    display: flex;
    flex-direction: column;
    justify-content: space-around;
    width: 300px;
    height: 100px;
    background-color: grey;
    position: absolute;
    left: 15%;
    top: 5%;
}

.holder {
    display: flex;
    flex-direction: row;
    align-items: center;
    justify-content: space-between;
    width: 100%;
    background-color: purple;
}

.button {
    display: flex;
    flex-direction: row;
    color: white;
    display: flex;
    width: 160px;
    margin: 5px;
    background-color: blue;
}
```

i add the text to the blue component directly in the first line, and to an inner div in the second line.

doing the same in bevy gives:
![image](https://github.com/bevyengine/bevy/assets/50659922/8ba37700-7c72-4c50-8346-2d8ddc87bef6)

using code 
```rust
use bevy::prelude::*;

fn main() {
    App::new()
        .add_plugins(DefaultPlugins)
        .add_systems(Startup, setup)
        .run();
}

fn setup(mut commands: Commands, asset_server: Res<AssetServer>) {
    let font = asset_server.load("FiraMono-Medium.ttf");
    let text_style = TextStyle {
        font,
        font_size: 14.,
        color: Color::WHITE,
    };
    commands.spawn(Camera2dBundle::default());

    commands
        .spawn(NodeBundle {
            style: Style {
                flex_direction: FlexDirection::Column,
                width: Val::Px(300.0),
                height: Val::Px(100.0),
                justify_content: JustifyContent::SpaceAround,
                position_type: PositionType::Absolute,
                left: Val::Percent(15.0),
                top: Val::Percent(5.0),
                ..Default::default()
            },
            background_color: Color::GRAY.into(),
            ..Default::default()
        })
        .with_children(|commands| {
            commands.spawn(NodeBundle{
                style: Style {
                    flex_direction: FlexDirection::Row,
                    align_items: AlignItems::Center,
                    justify_content: JustifyContent::SpaceBetween,
                    width: Val::Percent(100.0),
                    ..Default::default()
                },
                background_color: Color::PURPLE.into(),
                ..Default::default()
            }).with_children(|commands| {
                for i in 0..4 {
                    commands.spawn(TextBundle{
                        text: Text::from_section("text", text_style.clone()),
                        style: Style {
                            justify_content: if i % 2 == 0 { JustifyContent::FlexEnd } else { JustifyContent::DEFAULT },
                            width: Val::Px(160.0),
                            margin: UiRect::all(Val::Px(5.0)),
                            ..Default::default()
                        },
                        background_color: Color::BLUE.into(),
                        ..Default::default()
                    });
                }
            });

            commands.spawn(NodeBundle{
                style: Style {
                    flex_direction: FlexDirection::Row,
                    align_items: AlignItems::Center,
                    justify_content: JustifyContent::SpaceBetween,
                    width: Val::Percent(100.0),
                    ..Default::default()
                },
                background_color: Color::PURPLE.into(),
                ..Default::default()
            }).with_children(|commands| {
                for i in 0..4 {
                    commands.spawn(NodeBundle{
                        style: Style {
                            width: Val::Px(160.0),
                            margin: UiRect::all(Val::Px(5.0)),
                            justify_content: if i % 2 == 0 { JustifyContent::FlexEnd } else { JustifyContent::DEFAULT },
                            ..Default::default()
                        },
                        background_color: Color::BLUE.into(),
                        ..Default::default()
                    }).with_children(|tc| {
                        tc.spawn(TextBundle {
                            text: Text::from_section("text", text_style.clone()),
                            ..Default::default()
                        });
                    });
                }
            });
        });
}
```

i can spend some time trying to fix it if someone can point me in the right direction (or to prior discussions etc).

my guess is both are related to text nodes not reporting their calculated sizes back up the hierarchy for parents to size/position them (and themselves) correctly.

**Comment by rparrett** [comment]
This doesn't seem specific to text. If I replace the second line's text node a NodeBundle the same size as the text,
```rust
tc.spawn(NodeBundle {
    background_color: Color::BLACK.into(),
    style: Style {
        width: Val::Px(28.),
        height: Val::Px(12.),
        ..default()
    },
    ..default()
});
```
I see the same behavior.

**Comment by rparrett** [comment]
Flexbox is too confusing for me to say whether this is a bug or not.

But if I replace the second line's text container node's
```rust
width: Val::Px(160.0),
```
with
```rust
flex_basis: Val::Px(160.0),
```
Things seem to behave as expected.

Any insight, @nicoburns ?

**Comment by robtfm** [comment]
> This doesn't seem specific to text

agreed, screenshot (chrome vs bevy) adding that as line 3
![image](https://github.com/bevyengine/bevy/assets/50659922/6c8035f7-18ed-4b19-a985-7a3abd542aef)

i guess that means it's a taffy issue

**Comment by robtfm** [comment]
simplified
```html
<!DOCTYPE html>
<html>

<head> 
    <link rel="stylesheet" href="buttons.css"> 
</head>
 
<body>
    <div class="screen">
        <div class="holder">
            <div class="button">
                <div></div>
            </div>
        </div>
    </div>
</body>  
</html> 
```
```css
.screen {
    display: flex;
    flex-direction: column;
    justify-content: space-around;
    width: 100px;
    height: 100px;
    background-color: grey;
    position: absolute;
    left: 15%;
    top: 100px;
}

.holder {
    display: flex;
    flex-direction: row;
    background-color: purple;
}

.button {
    display: flex;
    width: 200px;
    height: 200px;
    margin: 5px;
    background-color: blue;
}
```
vs
```rust
use bevy::prelude::*;

fn main() {
    App::new()
        .add_plugins(DefaultPlugins)
        .add_systems(Startup, setup)
        .run();
}

fn setup(mut commands: Commands) {
    commands.spawn(Camera2dBundle::default());

    commands
        .spawn(NodeBundle {
            style: Style {
                flex_direction: FlexDirection::Column,
                width: Val::Px(100.0),
                height: Val::Px(100.0),
                justify_content: JustifyContent::SpaceAround,
                position_type: PositionType::Absolute,
                left: Val::Percent(15.0),
                top: Val::Px(100.0),
                ..Default::default()
            },
            background_color: Color::GRAY.into(),
            ..Default::default()
        })
        .with_children(|commands| {
            commands.spawn(NodeBundle{
                style: Style {
                    flex_direction: FlexDirection::Row,
                    ..Default::default()
                },
                background_color: Color::PURPLE.into(),
                ..Default::default()
            }).with_children(|commands| {
                commands.spawn(NodeBundle{
                    style: Style {
                        width: Val::Px(200.0),
                        height: Val::Px(200.0),
                        margin: UiRect::all(Val::Px(5.0)),
                        ..Default::default()
                    },
                    background_color: Color::BLUE.into(),
                    ..Default::default()
                }).with_children(|tc| {
                    tc.spawn(NodeBundle::default());
                });
            });
        });
}
```
==
![image](https://github.com/bevyengine/bevy/assets/50659922/a19ee5b0-0695-4acf-81c0-76ab5bc4778d)
