### ISSUE TITLE
Bevy freezes on Wayland

### ISSUE THREAD

**Issue by ColonelThirtyTwo** [bevyengine/bevy#10546]
## Bevy version

Tested both 0.12 and commit `18d001d27ce475388743d9825f2833ce51f5b20d` (current HEAD as of writing)

## \[Optional\] Relevant system information

Arch Linux, Hyprland compositor v0.30.0, laptop with AMD / Nvidia hybrid graphics.

## What you did

In `bevy/examples`, run `cargo run --example button --features wayland`, and attempt to press the button

## What went wrong

The button does not highlight on hover or clicking as expected. The cursor is stuck on the "text entry" cursor. The window does not respond to window closing, and must be closed via Ctrl+C from the console.

If I add a simple system that prints on update, the system only prints 5 times before stopping.

## Additional information

Removing the `wayland` feature from bevy fixes the issue.

Output of `env RUST_LOG=debug cargo run --example button --features wayland` (unfortunately includes coloring escape sequences): [log.txt](https://github.com/bevyengine/bevy/files/13340572/log.txt)

**Comment by badcodecat** [comment]
Same thing happening to me using KDE Wayland, rust 1.76.0, and bevy main.

**Comment by WarrenHood** [comment]
Can confirm that this happens for me using Hyprland on Arch, with Nvidia 550 drivers. All bevy apps/examples (eg. breakout) completely freeze when enabling the `wayland` feature. x11 works fine (aside from resizing the window causing a panic when the window surface gets outdated - but that's a different issue issue)

**Comment by Friz64** [comment]
I suspect this is https://github.com/gfx-rs/wgpu/issues/4775 (fixed in https://github.com/gfx-rs/wgpu/pull/4967). I've made a fork of wgpu 0.19 that includes this fix.

```toml
[patch.crates-io]
wgpu = { git = "https://github.com/Friz64/wgpu.git", branch = "v0.19-4967" }
wgpu-types = { git = "https://github.com/Friz64/wgpu.git", branch = "v0.19-4967" }
naga = { git = "https://github.com/Friz64/wgpu.git", branch = "v0.19-4967" }
```

Adding this to the bottom of bevy's Cargo.toml (or any bevy project's Cargo.toml) should fix the issue. Can anyone confirm this?
