### ISSUE TITLE
Segfault in App::finish() with bevy_core_pipeline

### ISSUE THREAD

**Issue by UkoeHB** [bevyengine/bevy#10875]
## Bevy version

v0.12.1

## Relevant system information

MacOS M1 Max v12.5.1.

## What you did

Compile basic program with nightly rust and `opt-level = 3` for dev dependencies.

`rust-toolchain.toml`
```toml
[toolchain]
channel = "nightly-2023-12-04"
```

`Cargo.toml`
```toml
[package]
name = "segfault"
version = "0.0.1"
edition = "2021"

[dependencies]
bevy = { version = "0.12",  default-features = false, features = [ "bevy_core_pipeline" ] }

[profile.dev.package."*"]
opt-level = 3
```

`main.rs`
```rust
use bevy::prelude::*;

fn main() {
    App::new().add_plugins(DefaultPlugins).finish();
}
```

## What went wrong

It segfaults.

## Additional information

- I was unable to get anything from AddressSanitizer.
- It doesn't segfault with opt level 2, or without `bevy_core_pipeline`, or without nightly rust.
