### ISSUE TITLE
Using `bevy_gizmos` feature with `default-features=false` renders nothing (requires extra `bevy_pbr` feature)

### ISSUE THREAD

**Issue by bonsairobo** [bevyengine/bevy#10984]
## Bevy version

0.12

## What you did

Tried to use `bevy_gizmos` with the following `bevy` dependency configuration:

```toml
[dependencies.bevy]
version = "0.12"
default-features = false
features = ["bevy_gizmos"]
```

## What went wrong

Gizmos were not drawn.

## Additional information

The fix was to add the `bevy_pbr` feature:

```toml
[dependencies.bevy]
version = "0.12"
default-features = false
features = ["bevy_gizmos", "bevy_pbr"]
```

I think we just need to add an explicit dependency on `bevy_pbr` here:

https://github.com/bevyengine/bevy/blob/ca1874e6c612d73306173065242aaaa8733c9b20/Cargo.toml#L132
