### ISSUE TITLE
Compiling With trace_chrome Feature Fails to Select Version

### ISSUE THREAD

**Issue by cjburkey01** [bevyengine/bevy#11365]
## Bevy version

`0.12.1`

## Relevant system information

Running on macOS, but I'm not sure if it's related to that.

## What you did

Execute `cargo run --release --features bevy/trace_chrome` as per the [profiling doc](https://github.com/bevyengine/bevy/blob/main/docs/profiling.md#chrome-tracing-format).

## What went wrong

Received cargo error:

```
error: failed to select a version for the requirement `profiling-procmacros = "^1.0.13"`
candidate versions found which didn't match: 1.0.8, 1.0.7, 1.0.6, ...
location searched: crates.io index
required by package `profiling v1.0.13`
    ... which satisfies dependency `profiling = "^1"` (locked to 1.0.13) of package `bevy_render v0.12.1`
    ... which satisfies dependency `bevy_render = "^0.12.1"` (locked to 0.12.1) of package `bevy_internal v0.12.1`
    ... which satisfies dependency `bevy_internal = "^0.12.1"` (locked to 0.12.1) of package `bevy v0.12.1`
    ... which satisfies dependency `bevy = "^0.12.1"` (locked to 0.12.1) of package `cjs_whole_new_world v0.0.5 ...`
perhaps a crate was updated and forgotten to be re-vendored?
```

## Cargo.toml

I'll attach this even though I don't think there's anything wrong.

```toml
[dependencies]
bevy = "0.12.1"
bitvec = "1.0.1"
bevy_egui = "0.24.0"
leafwing-input-manager = "0.11.2"
noise = "0.8.2"
futures-lite = "2.2.0"
priority-queue = "1.3.2"
itertools = "0.12.0"
```
