### ISSUE TITLE
Investigate workspace-level dependencies

### ISSUE THREAD

**Issue by BD103** [bevyengine/bevy#12374]
> Good stuff. I'd like to look into workspace-level dependencies at some point too.

_Originally posted by @alice-i-cecile in https://github.com/bevyengine/bevy/issues/12313#issuecomment-1979531886_

[Workspace-level dependencies](https://doc.rust-lang.org/cargo/reference/workspaces.html#the-dependencies-table) allow for consistent dependency versions across multiple crates. They can be handy for keeping popular libraries, such as `serde`, `syn`, `toml_edit` and more in sync and reduce dependency duplication.

They can be specified with:

```toml
# Root Cargo.toml
[workspace.dependencies]
serde = "1.0.99999"
```

And can be used by a crate with:

```toml
[dependencies]
serde = { workspace = true }
# or
serde.workspace = true
```
