### ISSUE TITLE
Warnings about unused manifest key and no specified local path etc..

### ISSUE THREAD

**Issue by evrensen467** [bevyengine/bevy#13622]
How do I solve this?
```
warning: dependency (bevy) specified without providing a local path, Git repository, version, or workspace dependency to use. This will be considered an error in future versions
warning: unused manifest key: dependencies.bevy.verson
```

```toml
[package]
name = "diep"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = { verson = "0.13.2", features = ["dynamic_linking"] }

[profile.dev]
opt-level = 1

[profile.dev.package."*"]
opt-level = 3
```
