### ISSUE TITLE
Remove manual `--cfg docsrs` in `Cargo.toml` metadata

### ISSUE THREAD

**Issue by BD103** [bevyengine/bevy#14132]
## What problem does this solve or what need does it fill?

At the bottom of every public crate is the following:

```toml
[package.metadata.docs.rs]
rustdoc-args = ["-Zunstable-options", "--cfg", "docsrs"]
all-features = true
```

This allows code to check that it is building on docs.rs using `#[cfg(docsrs)]`. It's frequently used for nightly docs annotations, such as enabling auto-feature-documentation. The `--cfg docsrs` section of `rustdoc-args` can be removed, since it is now passed to **all** crates instead of just the main one being built.

## What solution would you like?

Remove `--cfg docsrs` from the `Cargo.toml`, and re-evaluate if `-Zunstable-options` is still necessary.

## Additional context

- https://github.com/rust-lang/docs.rs/pull/2390
- https://github.com/rust-lang/docs.rs/issues/2389
