### ISSUE TITLE
100% CPU on very simple scene

### ISSUE THREAD

**Issue by bbasics** [bevyengine/bevy#14359]
## Bevy version

0.14.0

## \[Optional\] Relevant system information

If you cannot get Bevy to build or run on your machine, please include:

Rust: `rustc 1.79.0 (129f3b996 2024-06-10)`
Linux: `Linux mars 5.19.0-38-generic #39~22.04.1-Ubuntu`
CPU: `AMD® Ryzen 5 5600x`
GPU: `Nvidia GeForce RTX 3060 Ti`

Cargo.toml:
```toml
[package]
name = "first_game"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = { version = "0.14.0", features = ["dynamic_linking", "bevy_dev_tools"] }
bevy_dev_tools = "0.14.0"
bevy_mod_picking = { version = "0.20.1", features = ["debug"]}

# Enable a small amount of optimization in debug mode.
[profile.dev]
opt-level = 1

# Enable a large amount of optimization in debug mode for dependencies.
[profile.dev.package."*"]
opt-level = 3

# Enable more optimization in release mode at the cost of compile time.
[profile.release]
# Compile the entire crate as one unit.
# Significantly slows compile times, marginal improvements.
codegen-units = 1
# Do a second optimization pass over the entire program, including dependencies.
# Slightly slows compile times, marginal improvements.
lto = "thin"

# Optimize for size in wasm-release mode to reduce load times and bandwidth usage on web.
[profile.wasm-release]
# Use release profile as default values.
inherits = "release"
# Optimize with size in mind (also try "s", sometimes it is better).
# This doesn't increase compilation times compared to -O3, great improvements.
opt-level = "z"
# Strip all debugging information from the binary to reduce file size.
strip = "debuginfo"
```

## What you did

```rust
use bevy::prelude::*;
use bevy_mod_picking::prelude::*;

fn main() {
    let mut app = App::new();
    app.add_plugins(DefaultPlugins);
    app.add_systems(Startup, setup);
    app.add_plugins(DefaultPickingPlugins);
    app.run();
}

#[derive(Component)]
struct Cube {
    click_counter: u32,
}

fn setup(
    mut commands: Commands,
    mut meshes: ResMut<Assets<Mesh>>,
    mut materials: ResMut<Assets<StandardMaterial>>,
) {
    // Cube
    commands.spawn((
        PbrBundle {
            mesh: meshes.add(Cuboid::new(1.0, 1.0, 1.0)),
            material: materials.add(Color::srgb_u8(124, 144, 255)),
            transform: Transform::from_xyz(0.0, 0.5, 0.0),
            ..default()
        },
        Cube { click_counter: 0 },
        On::<Pointer<Click>>::target_component_mut::<Cube>(|event, cube| {
            cube.click_counter += 1;
            println!(
                "Clicked on {:?} times {}",
                event.target(),
                cube.click_counter
            );
        }),
    ));
    // Light
    commands.spawn(PointLightBundle {
        point_light: PointLight {
            shadows_enabled: true,
            ..default()
        },
        transform: Transform::from_xyz(4.0, 8.0, 4.0),
        ..default()
    });
    // Camera
    commands.spawn(Camera3dBundle {
        transform: Transform::from_xyz(-2.5, 4.5, 9.0).looking_at(Vec3::ZERO, Vec3::Y),
        ..default()
    });
}
```

## What went wrong

When I move the mouse, I got 100% CPU usage on this very simple scene. I would expect a very low usage.

![image](https://github.com/user-attachments/assets/118b0c19-e27e-4314-b6e1-30b0c2432a7b)

I that normal? thanks in advance!
