### ISSUE TITLE
Linker error when using meshlet_processor feature on Linux

### ISSUE THREAD

**Issue by 66OJ66** [bevyengine/bevy#14400]
## Bevy version

0.14

## [Optional] Relevant system information
Toolchain: rustc 1.81.0-nightly (c6727fc9b 2024-07-12)
Operating System: openSUSE Tumbleweed

## What you did

I attempted to build my game with the `meshlet_processor` feature enabled.

## What went wrong

Several linker errors like the below are returned at the end of the build process e.g.
```
debug/deps/libmetis_sys-af905d4c1b076d70.rlib(cef2855204fe6acf-options.o):(.text): R_X86_64_32 relocation at offset 0x1a69 against symbol `.rodata' can not be used; recompile with -fPIC
```

I then added the mentioned flag via my project's config.toml file:
```toml
[target.x86_64-unknown-linux-gnu]
linker = "clang"
rustflags = ["-C", "link-arg=-fPIC"]
```

The built then failed again with this error:
```
debug/deps/libmetis_sys-36547e19c5cdc3ae.rlib(cef2855204fe6acf-gklib.o): relocation R_X86_64_32 against `.rodata' can not be used when making a PIE object; recompile with -fPIE
/usr/bin/ld: failed to set dynamic section sizes: bad value
```

So I then tried compiling again with that additional flag:
```toml
[target.x86_64-unknown-linux-gnu]
linker = "clang"
rustflags = ["-C", "link-arg=-fPIC", "-C", "link-arg=-fPIE"]
```

And got the same error again.

This might be an issue with the `metis`  crate itself, but figured it was worth raising here first.
