### ISSUE TITLE
`Reader` not a trait when running custom asset reader example outside bevy

### ISSUE THREAD

**Issue by robertdodd** [bevyengine/bevy#14565]
## Bevy version

0.14.0

## \[Optional\] Relevant system information

Rust: 1.80.0
OS 1: Ubuntu 22.04 LTS
OS 2: macOS Sonoma 14.5

## What you did

I copied the `custom_asset_reader` example to a new project, but it failed with an error saying that `Reader` is a type alias and not a trait.

Steps to reproduce (assuming cwd contains the `bevy` folder):

```shell
cargo new bevy_issue_test
cd bevy_issue_test
cargo add bevy
rm src/main.rs
cp ../bevy/examples/asset/custom_asset_reader.rs src/main.rs
cargo run
```

## What went wrong

I get 2 identical error messages saying that `Reader` is not a trait:

```
error[E0404]: expected trait, found type alias `Reader`
  --> src/main.rs:18:64
   |
18 |     async fn read<'a>(&'a self, path: &'a Path) -> Result<impl Reader + 'a, AssetReaderError> {
   |                                                                ^^^^^^ type aliases cannot be used as traits
```

## Additional information

**Type Definition**

When I go to the `Reader` symbol, it takes me to the following type, which is not the same `Reader` in the source code:

```rust
// ~/.cargo/registry/src/index.crates.io-6f17d22bba15001f/bevy_asset-0.14.0/src/io/mod.rs:79
pub type Reader<'a> = dyn AsyncReadAndSeek + Unpin + Send + Sync + 'a;
```

**What Worked**

Using any of these bevy dependencies worked:

```toml
bevy = { path = "../bevy" } # at "v0.14.0" tag
bevy = { git = "https://github.com/bevyengine/bevy", branch = "main" }
```

**What didn't work**

```toml
bevy = "0.14.0"
bevy = { git = "https://github.com/bevyengine/bevy", tag = "v0.14.0" }
```
