### ISSUE TITLE
All UI elements randomly disappear for some frames on specific android devices

### ISSUE THREAD

**Issue by MarcoMeijer** [bevyengine/bevy#14710]
## Bevy version

Bevy 0.14.1

##  Relevant system information

Samsung Galaxy A34
Cargo 1.80.0
Built using https://github.com/NiklasEi/xbuild

## What you did

Rendered user interface and a regular sprite.

```rs
use bevy::prelude::*;

#[bevy_main]
fn main() {
    let mut app = App::new();
    app.add_plugins(DefaultPlugins).add_systems(Startup, setup);
    app.run();
}

fn setup(mut commands: Commands, asset_server: Res<AssetServer>) {
    commands.spawn((Camera2dBundle::default(), IsDefaultUiCamera));
    commands.spawn((
        NodeBundle {
            style: Style {
                width: Val::Px(500.0),
                height: Val::Px(125.0),
                ..default()
            },
            ..default()
        },
        UiImage::new(asset_server.load("branding/bevy_logo_dark_big.png")),
    ));
    commands.spawn(SpriteBundle {
        transform: Transform::from_xyz(0., 0., 0.),
        sprite: Sprite {
            custom_size: Some(Vec2::new(500., 125.)),
            ..default()
        },
        texture: asset_server.load("branding/bevy_logo_dark_big.png"),
        ..default()
    });
}
```

## What went wrong

The ui image is flickering, but the regular sprite is not flickering.

## Additional information

https://github.com/user-attachments/assets/e5c3c48b-6470-440b-9392-e4a2257ec75b

One of my play testers for my game has this issue, this was recorded on their phone. Other people, including me don't have this issue so it could be a device related issue. This flickering also happens on text and 9-slices (not shown in example).

This issue happened once to me, but never again after that. But on this persons phone it seems to happen almost always. 

This might be a related issue: https://github.com/gfx-rs/wgpu/issues/2399, but I am not sure since it only happens on UI elements as shown in the video.

This pull request seems to be solving a similar issue: https://github.com/bevyengine/bevy/pull/13462.

Maybe this bug has something to do with system ordering?

**Comment by Nihilistas** [comment]
@MarcoMeijer how are you using xbuild with bevy, exactly? It would be nice if you provided more of the project code. I am having trouble even running bevy with xbuild in the first place.

**Comment by MarcoMeijer** [comment]
@Nihilistas 
I have a manifest.yaml file containing this:
```yaml
android:
  gradle: true
  icon: "assets/icon.png"
  manifest:
    package: "com.x.y"
    version_code: 13
    uses_permission:
      - name: "android.permission.INTERNET"
    application:
      label: "x"
      theme: "@android:style/Theme.DeviceDefault.NoActionBar.Fullscreen"
      activities:
        - orientation: "landscape"
```

And a cargo.toml file containing this:
```toml
[package]
name = "bug-report"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = { version = "0.14.1" }

[lib]
crate-type = ["staticlib", "cdylib"]

[package.metadata.android]
package = "org.x.y"
apk_name = "x"
assets = "assets"
resources = "assets/android-res"
strip = "strip"
build_targets = ["aarch64-linux-android"]

[target."cfg(target_os = \"android\")".dependencies.cpal]
version = "0.15"
features = ["oboe-shared-stdcxx"]

[package.metadata.android.sdk]
target_sdk_version = 31

[package.metadata.android.application]
icon = "@mipmap/ic_launcher"
theme = "@android:style/Theme.DeviceDefault.NoActionBar.Fullscreen"
label = "x"

[package.metadata.android.signing.release]
path = "<PATH_TO_KEYSTORE_FILE>"
keystore_password = "<PASSWORD_TO_KEYSTORE_FILE>"

[package.metadata.android.application.activity]
orientation = "landscape"

[[package.metadata.android.uses_permission]]
name = "android.permission.INTERNET"
```

For my use case I needed internet permissions but you can probably remove that.

And that's it. Then I just run `x build --platform android --store play`.
