### ISSUE TITLE
Packaged as .app on the macOS platform, assets cannot be read.

### ISSUE THREAD

**Issue by mzdk100** [bevyengine/bevy#15618]
I used the following code:
```rust
use bevy::prelude::*;

fn main() {
    App::new()
        .add_plugins(DefaultPlugins)
        .add_systems(Startup, setup)
        .run();
}

fn setup(asset_server: Res<AssetServer>, mut commands: Commands) {
    commands.spawn(AudioPlayer::<AudioSource>(
        asset_server.load("test.ogg"),
    ));
}
```
Directly debug and run without any problems, audio can be played normally:
```shell
cargo run --target aarch64-apple-darwin
```
However, if packaged in .app format (for distribution purposes), files in assets cannot be read and audio cannot be played.
```toml
[package.metadata.bundle]
name = "myapp"
identifier = "com.sscn.myapp"
icon = ["logo_32x32.png", "platform/macos/logo_128x128.png"]
resources = ["assets"]
copyright = "Copyright (C) 2024. All rights reserved."
category = "Game"
long_description = """
A role-playing card game.
```
```shell
cargo install cargo-bundle
cargo bundle --release --target aarch64-apple-darwin
```
How should I achieve it? Thank you.
