### ISSUE TITLE
.add_systems DONT WORK

### ISSUE THREAD

**Issue by KeiMuriKoe** [bevyengine/bevy#17130]
## Bevy version

current main version - 0.15

## What you did

I wanted to try out a new engine (Bevy) and started following the "Get Started" documentation. Things went off track when I tried to use ```app.add_systems``` It seemed like such a basic and straightforward function that should definitely work, so I feel like I must be missing something. But for some reason, it just doesn't work—the simplest example code doesn't run for me. Everything else I've tested so far works perfectly fine for me. Fot example connecting plugins.

```
use bevy::prelude::*;

fn main() {
    let mut app = App::new();
    app.add_systems(Startup, hello_world);
    app.run();
}

fn hello_world() {
    println!("hello world");
}
```

Windows 11.

## What went wrong

INFO bevy_render::renderer: AdapterInfo { name: "AMD Radeon RX 6700 XT", vendor: 4098, device: 29663, device_type: DiscreteGpu, driver: "AMD proprietary driver", driver_info: "24.4.1 (AMD proprietary shader compiler)", backend: Vulkan }
error: process didn't exit successfully: `target\debug\my_bevy_game.exe` (exit code: 0xc0000005, STATUS_ACCESS_VIOLATION)

## Additional information

![Image](https://github.com/user-attachments/assets/c8aa8c86-0549-41de-9fca-28d508aa58f7)
![Image](https://github.com/user-attachments/assets/4f901353-eb65-4929-8b18-8ee00e689bde)

**Comment by copygirl** [comment]
Unsure about the error, but you'll need to use your own [`Schedule`](https://docs.rs/bevy/latest/bevy/ecs/schedule/struct.Schedule.html) or the [`ScheduleRunnerPlugin`](https://docs.rs/bevy/latest/bevy/app/struct.ScheduleRunnerPlugin.html) (part of [`MinimalPlugins`](https://docs.rs/bevy/latest/bevy/struct.MinimalPlugins.html)).

**Comment by viridia** [comment]
Interesting. Curious to know if adding the `DefaultPlugins` to `app` makes it work.

**Comment by PhantomMorrigan** [comment]
yeah you _need_ `DeafultPlugins` or `MinimalPlugins`, otherwise you App won't have a runner, and thus can't run iirc.

**Comment by viridia** [comment]
If that's the case, then the example in the documentation is wrong.

**Comment by PhantomMorrigan** [comment]
Actually I retract what I said earlier, this isn't correct. Also, I can't actually reproduce this on Linux at least.

**Comment by KeiMuriKoe** [comment]
> Interesting. Curious to know if adding the `DefaultPlugins` to `app` makes it work.

if add ```DefaultPlugins ``` it works, but not with ```add_systems```

**Comment by KeiMuriKoe** [comment]
> Actually I retract what I said earlier, this _should_ work. Also, It does actually work, at least on Linux.
> 
> Try checking if there is some antivirus software breaking things? I've at least seen that happen before.

i dont have any)  

I have completely removed the antivirus from my Windows system and I don’t use any third-party ones. Also, I can run the example project and add the default plugin. All it works. I used a clean installation and tried running ```cargo clean```, but none of that helped me. 

i use 23H2 Windows ver. OS 22631, 4602 build

**Comment by skimmedsquare** [comment]
Just a note that I can't repro the crash with the example code on Mac.

**Comment by BenjaminBrienen** [comment]
![Image](https://github.com/user-attachments/assets/829a7297-0fd7-4bc2-9ab3-8d4c74096ae6)
Can't reproduce

**Comment by jmskov** [comment]
Are your GPU drivers up to date? I would also try to reinstall the GPU driver.

**Comment by KeiMuriKoe** [comment]
> ![Image](https://github.com/user-attachments/assets/829a7297-0fd7-4bc2-9ab3-8d4c74096ae6) Can't reproduce

![Image](https://github.com/user-attachments/assets/b9c61125-9cf3-4b45-8c40-1da5812bf9e8)

I suspect this is related to my large list in ```Cargo.toml```, but I haven’t added anything that isn’t in the Quick Start section of the Bevy docs.I also used ```cargo update``` to get version 0.15.1, and it seems to have worked, but for some reason, ```Cargo.toml``` still shows 0.15.0.

**Comment by PhantomMorrigan** [comment]
Try disabling dynamic linking, maybe? (Just a guess)

**Comment by BenjaminBrienen** [comment]
Can you please post your Cargo.toml?

**Comment by copygirl** [comment]
@KeiMuriKoe From the screenshot I can see you depend on `bevy` version `0.15` which is equivalent to `>=0.15.0, <0.16.0`, so it's not surprising it updated to a newer version. The same would happen if you specified `0.15.0`. See [here](https://doc.rust-lang.org/cargo/reference/specifying-dependencies.html).

**Comment by eidloi** [comment]
@KeiMuriKoe There is an issue with wgpu on Windows where you get this error. In my case my laptop has both a dedicated and an iGPU and I had to specify to always use the dedicated GPU in the Nvidia driver settings (by default it just "picks the best" for the process / power saving scheme). I recall there is a similar setting for AMD GPUs as well (the Windows setting didn't work for me), perhaps you can try to look for that.

**Comment by KeiMuriKoe** [comment]
> Can you please post your Cargo.toml?

no problem
```[package]
name = "my_bevy_game"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = { version = "0.15", features = ["dynamic_linking"] }
log = { version = "*", features = ["max_level_debug", "release_max_level_warn"] }

[profile.dev]
opt-level = 1

[profile.dev.package."*"]
opt-level = 3

#[workspace]
#resolver = "2" # Important! wgpu/Bevy needs this!

[profile.release]
codegen-units = 1
lto = "thin"

[profile.wasm-release]
inherits = "release"
opt-level = "s"
strip = "debuginfo"
```

**Comment by KeiMuriKoe** [comment]
> [@KeiMuriKoe](https://github.com/KeiMuriKoe) There is an issue with wgpu on Windows where you get this error. In my case my laptop has both a dedicated and an iGPU and I had to specify to always use the dedicated GPU in the Nvidia driver settings (by default it just "picks the best" for the process / power saving scheme). I recall there is a similar setting for AMD GPUs as well (the Windows setting didn't work for me), perhaps you can try to look for that.
> 
> edit: this is the ticket I pinged but couldn't yet follow up: [gfx-rs/wgpu#5879](https://github.com/gfx-rs/wgpu/issues/5879) There is also an AMD specific bug open: [gfx-rs/wgpu#6329](https://github.com/gfx-rs/wgpu/issues/6329) but I don't think an empty project would trigger that issue since it's shader-related

Sounds very interesting! What do I need to do to test this hypothesis?
I tried removing the line ```[workspace] 
resolver = "2" # Important! wgpu/Bevy needs this!```
from the ```Cargo.toml``` file and used ```cargo run``` — it didn’t help.
I also tried ```cargo clean``` followed by ```cargo run``` again — that didn’t work either.

**Comment by KeiMuriKoe** [comment]
> [@KeiMuriKoe](https://github.com/KeiMuriKoe) From the screenshot I can see you depend on `bevy` version `0.15` which is equivalent to `>=0.15.0, <0.16.0`, so it's not surprising it updated to a newer version. The same would happen if you specified `0.15.0`. See [here](https://doc.rust-lang.org/cargo/reference/specifying-dependencies.html).

Oh. THX YOU! REally helpful information

**Comment by KeiMuriKoe** [comment]
> Try disabling dynamic linking, maybe? (Just a guess)

I don’t know who you are, hero. Honestly, I tested your theory last, thinking there’s no way it would work… How wrong I was. By removing just one line,``` features = ["dynamic_linking"]``` it started working.

![Image](https://github.com/user-attachments/assets/a4f918ba-ce4f-4066-bd57-e16fe51c5cba)

**Comment by KeiMuriKoe** [comment]
Is it ok? If not - waiting room for someone reproduce it

**Comment by PhantomMorrigan** [comment]
Okay, could you give some info on your installed rust toolchain?

**Comment by KeiMuriKoe** [comment]
> Okay, could you give some info on your installed rust toolchain?

I’m not entirely sure what you mean by "toolchain." Perhaps you mean this: I installed the latest MSVC, the latest Windows SDK, and the C++ CMake tools for the Windows component.

**Comment by PhantomMorrigan** [comment]
What I mean is the info you are given by running `rustup show`. Would be really helpful.

**Comment by KeiMuriKoe** [comment]
> What I mean is the info you are given by running `rustup show`. Would be really helpful.

```
Default host: x86_64-pc-windows-msvc
rustup home:  C:\Users\Den\.rustup

installed toolchains
--------------------

stable-x86_64-pc-windows-msvc (default)
nightly-x86_64-pc-windows-msvc

active toolchain
----------------

nightly-x86_64-pc-windows-msvc (overridden by 'D:\apps\bevy projects\my_bevy_game\rust-toolchain.toml')
rustc 1.85.0-nightly (45d11e51b 2025-01-01)
```

**Comment by PhantomMorrigan** [comment]
try running `rustup update`, and check if the error still occurs with dynamic linking?

**Comment by KeiMuriKoe** [comment]
> rustup update

It didn't help.

**Comment by jmskov** [comment]
Try running `rustup default stable` or update `'D:\apps\bevy projects\my_bevy_game\rust-toolchain.toml` to use the stable toolchain instead of the nightly build to rule out a problem there.

**Comment by KeiMuriKoe** [comment]
> Try running `rustup default stable` or change `D:\apps\bevy projects\my_bevy_game\rust-toolchain.toml` to use the stable toolchain instead of the nightly build to rule out a problem there.

![Image](https://github.com/user-attachments/assets/7b3d94f9-95c9-4052-97b8-90d55a9aa689)

**Comment by jmskov** [comment]
Tried on my PC w/ 6900XT GPU, no issues. Here is my GPU driver info from running the game:

<img width="678" alt="Image" src="https://github.com/user-attachments/assets/d14496e4-eefe-4d72-97a1-d1ede672f391" />

**Comment by PhantomMorrigan** [comment]
The example code doesn't add any plugins, and thus _doesn't_ interact with the GPU.

**Comment by KeiMuriKoe** [comment]
> Tried on my PC w/ 6900XT GPU, no issues. Here is my GPU driver info from running the game:
> 
> <img alt="Image" width="678" src="https://private-user-images.githubusercontent.com/3778578/400657745-d14496e4-eefe-4d72-97a1-d1ede672f391.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzYyNDg3MjAsIm5iZiI6MTczNjI0ODQyMCwicGF0aCI6Ii8zNzc4NTc4LzQwMDY1Nzc0NS1kMTQ0OTZlNC1lZWZlLTRkNzItOTdhMS1kMWVkZTY3MmYzOTEucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI1MDEwNyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNTAxMDdUMTExMzQwWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MGJiZmYzZjU4YmZmZjgxNjliODEwNzU4MjI1Yjg1MjI3NDEyOWFmYTVlNzZiMTFiZjk4ZDEyMjFmMjQ2ZTViYyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.FjMQ49YL8_5YPeRvtp1ESSqMeD9rjkM3gK2GaZNyqak">

did you use dynamic_linking?

**Comment by jmskov** [comment]
Yes, I used dynamic_linking and the other features in your Cargo.toml.

**Comment by 0not** [comment]
I can reproduce this issue when compiling with `--release` and dynamic linking with LLD on Windows 11. Debug builds work fine. Disabling dynamic linking also works fine. Dynamic linking with the default linker DOES NOT work, with a slightly different error (no output and process did not end without CTRL+C).

Device and OS details:
```
Processor	AMD Ryzen 7 PRO 7840U w/ Radeon 780M Graphics     3.30 GHz
Installed RAM	32.0 GB (30.7 GB usable)

Edition	Windows 11 Pro
Version	23H2
Installed on	‎12/‎7/‎2023
OS build	22631.4751
Experience	Windows Feature Experience Pack 1000.22700.1055.0
```
Output of `rustup show`:
```
> rustup show                                               
Default host: x86_64-pc-windows-msvc
rustup home:  C:\Users\xxxxxx\.rustup

stable-x86_64-pc-windows-msvc (default)
rustc 1.84.0 (9fc6b4312 2025-01-07)
```
Minimal reproducible example:
```rust
use bevy::prelude::*;

fn main() {
    // Program executes correctly if I don't add a system
    App::new().add_systems(Update, setup).run();
}

fn setup() {
    println!("Setup");
}
```
Error when dynamic linking is enabled with LLD (and `--release`):
```
    Finished `release` profile [optimized] target(s) in 2.72s
     Running `target\release\examples\custom_schedule.exe`
error: process didn't exit successfully: `target\release\examples\custom_schedule.exe` (exit code: 0xc0000005, STATUS_ACCESS_VIOLATION)
```
Error when dynamic linking is enabled with default linker (and `--release`). I had to hit CTRL+C to quit the process because the process ran without any output and did not exit.
```
    Finished `release` profile [optimized] target(s) in 6m 22s
     Running `target\release\examples\custom_schedule.exe`
error: process didn't exit successfully: `target\release\examples\custom_schedule.exe` (exit code: 0xc000013a, STATUS_CONTROL_C_EXIT)
```

I am running this in an example that is part of a workspace.

Workspace `Cargo.toml`
```toml
[workspace]
resolver = "2" # Needed for wgpu/Bevy
members = [ "xxxx" ]


# Enable a small amount of optimization in the dev profile.
[profile.dev]
opt-level = 1

# Enable a large amount of optimization in the dev profile for dependencies.
[profile.dev.package."*"]
opt-level = 3

# Enable more optimization in the release profile at the cost of compile time.
[profile.release]
# Compile the entire crate as one unit.
# Slows compile times, marginal improvements.
codegen-units = 1
# Do a second optimization pass over the entire program, including dependencies.
# Slows compile times, marginal improvements.
lto = "thin"

# Optimize for size in the wasm-release profile to reduce load times and bandwidth usage on web.
[profile.wasm-release]
# Default to release profile values.
inherits = "release"
# Optimize with size in mind (also try "z", sometimes it is better).
# Slightly slows compile times, great improvements to file size and runtime performance.
opt-level = "s"
# Strip all debugging information from the binary to slightly reduce file size.
strip = "debuginfo"
```
Crate `Cargo.toml` (the extra dependencies are not relevant to the example, but perhaps with dynamic linking they matter):
```toml
[package]
name = "xxxxx"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = { version = "0.15", features = ["dynamic_linking"] }
bevy-inspector-egui = "0.28.1"
iyes_perf_ui = { git = "https://github.com/IyesGames/iyes_perf_ui.git" }
rand = "0.8.5"
```
And finally, my `.cargo/config.toml`:
```toml
[env]
# Eliminates ERROR messages relating to D3D12 on Windows
# Full error:
# ERROR wgpu_hal::auxil::dxgi::exception: ID3D12CommandQueue::ExecuteCommandLists: Using IDXGISwapChain::Present on Command List (0x000002AA96478D20:'Internal DXGI CommandList'): Resource state (0x464FF090: D3D12_RESOURCE_STATE_RENDER_TARGET) of resource (0x000002AA964E9EE0:'Unnamed ID3D12Resource Object') (subresource: 0) is invalid for use as a PRESENT_SOURCE.  Expected State Bits (all): 0x464FF070: D3D12_RESOURCE_STATE_[COMMON|PRESENT], Actual State: 0x464FF050: D3D12_RESOURCE_STATE_RENDER_TARGET, Missing State: 0x0: D3D12_RESOURCE_STATE_[COMMON|PRESENT]. [ EXECUTION ERROR #538: INVALID_SUBRESOURCE_STATE]
WGPU_BACKEND = "vulkan"

# for Linux
[target.x86_64-unknown-linux-gnu]
linker = "clang"
rustflags = ["-C", "link-arg=-fuse-ld=lld"]


# for Windows
[target.x86_64-pc-windows-msvc]
linker = "rust-lld.exe"
```
# Summary
I cannot run programs compiled with `--release` with `bevy/dynamic_linking` enabled. This is true for both LLD and the default linker on Windows 11. If I don't add a system, everything works fine (program runs and exits with no error).

I'm going to try a clean project and report back.

**Comment by 0not** [comment]
I set up a new project with the following `Cargo.toml`

```toml
[package]
name = "bevy_test"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = { version = "0.15", default-features = false, features = ["dynamic_linking"] }
```
The rust code did not change:
```rust
use bevy::prelude::*;

fn main() {
    App::new().add_systems(Update, setup).run();
}

fn setup() {
    println!("Setup");
}
```
Results:
```
> cargo run --release
    Finished `release` profile [optimized] target(s) in 0.18s
     Running `target\release\bevy_test.exe`
Setup
```

Next I tried adding the following to `Cargo.toml`:
```toml
[profile.release]
lto = "thin"
```
And ran into the error where the program runs but does not print "Setup". (I'm using the default linker.)

After switching back to LLD:
```
> cargo run --release
    Finished `release` profile [optimized] target(s) in 0.23s
     Running `target\release\bevy_test.exe`
error: process didn't exit successfully: `target\release\bevy_test.exe` (exit code: 0xc0000005, STATUS_ACCESS_VIOLATION)
```
# Summary
Dynamic linking does not work (with either LLD or the default linker) if `lto = "thin"` in the release profile.

What does this bug indicate? Why do the two linkers behave slightly differently? Should we report this elsewhere, or is it a bug with bevy?
