### ISSUE TITLE
Periodic drops in fps

### ISSUE THREAD

**Issue by Ruttie2006** [bevyengine/bevy#18050]
## Bevy version
Version `0.15.3`, with features: [`"animation", "bevy_animation", "bevy_asset", "bevy_audio", "bevy_color", "bevy_core_pipeline", "bevy_gilrs", "bevy_gizmos", "bevy_gltf", "bevy_mesh_picking_backend", "bevy_pbr", "bevy_picking", "bevy_render", "bevy_scene", "bevy_sprite", "bevy_sprite_picking_backend", "bevy_state", "bevy_text", "bevy_ui", "bevy_ui_picking_backend", "bevy_window", "bevy_winit", "default_font", "multi_threaded", "smaa_luts", "sysinfo_plugin", "tonemapping_luts", "x11", "qoi", "shader_format_spirv"`]
(I have seen this happen with default features too)

## What you did

Write a simply app that uses iyes_perf_ui to observe fps.
Code:
```rs
use bevy::{diagnostic::FrameTimeDiagnosticsPlugin, prelude::*, render::diagnostic::RenderDiagnosticsPlugin};
use iyes_perf_ui::{entries::PerfUiFramerateEntries, PerfUiPlugin};

fn main() -> AppExit {
    App::new()
        .add_plugins(DefaultPlugins)
        .add_plugins(FrameTimeDiagnosticsPlugin)
        .add_plugins(bevy::diagnostic::EntityCountDiagnosticsPlugin)
        .add_plugins(bevy::diagnostic::SystemInformationDiagnosticsPlugin)
        .add_plugins(RenderDiagnosticsPlugin)
        .add_plugins(PerfUiPlugin)
        .add_systems(Startup, init)
        .run()
}

fn init(mut commands: Commands) {
    commands.spawn(Camera2d);
    commands.spawn(PerfUiFramerateEntries::default());
}
```

## What went wrong

Every so often fps drop drastically for some (fairly short) period of time.
This can be observed in `iyes_perf_ui` by looking at the `FPS (min)` and `Frame Time (max)` values.

## Additional information

Video: https://github.com/user-attachments/assets/8ae90b2f-8768-454e-a33a-0ff224e1c422
Ran using `cargo run --release`
`log` and `tracing` crates set to `"max_level_info", "release_max_level_warn"`

**Comment by alice-i-cecile** [comment]
Can you show us what this looks like via `tracing`? The system spans will be a critical clue, and it eliminates the risk that this is actually caused by `iyes_perf_ui`.

**Comment by Ruttie2006** [comment]
> Can you show us what this looks like via `tracing`? The system spans will be a critical clue, and it eliminates the risk that this is actually caused by `iyes_perf_ui`.

Would using the `trace_chrome` feature be fine?
I can't provide any traces today, but I can record and give them tomorrow.

**Comment by alice-i-cecile** [comment]
That would be totally fine.

**Comment by Ruttie2006** [comment]
Here is the trace file: [trace-1740700934508643.zip](https://github.com/user-attachments/files/19024637/trace-1740700934508643.zip)
There's one of the extra long frames at `8301854428` (id `366328`).
The longest task seems to be `VkQueuePresentKHR`, which seems like a GPU bottleneck, however there's not much to render so that seems weird to me.

![Image](https://github.com/user-attachments/assets/435849f4-1fcf-4d8f-a5b7-00870a9df6d4)

**Comment by Ruttie2006** [comment]
Curiously enough, a trace generated with `present_mode: PresentMode::Mailbox` seems to have a different problem:

![Image](https://github.com/user-attachments/assets/ecf16035-4172-4675-9854-c6e4aeadc68e)

(I won't post the entire trace here since it's 1.3GB)
As can be seen in the image, `vkAcquireNextImageKHR` seems to be the problem here.
I'm quite confused as what could be going wrong with these two.

**Comment by arcln** [comment]
I have the exact same issue, every now or so frames are taking twice the time they should (one frame is skipped), with the trace showing that my code is not the bottleneck. In my case I don't use Vulkan, and the bottleneck seem to be "prepare_windows" (I don't know how to interpret that).

```toml
[workspace.dependencies.bevy]
version = "0.15.3"
default-features = false
features = [
  # Bevy functionality:
  "multi_threaded",     # Run with multithreading
  #"bevy_asset",        # Assets management
  #"bevy_audio",        # Builtin audio
  "bevy_gilrs",         # Gamepad input support
  #"bevy_scene",        # Scenes management
  "bevy_winit",         # Window management (cross-platform Winit backend)
  "bevy_render",        # Rendering framework core
  "bevy_core_pipeline", # Common rendering abstractions
  #"bevy_gizmos",       # Support drawing debug lines and shapes
  "bevy_sprite",        # 2D (sprites) rendering
  #"bevy_pbr",          # 3D (physically-based) rendering
  #"bevy_gltf",         # GLTF 3D assets format support
  "bevy_text",          # Text/font rendering
  #"bevy_ui",           # UI toolkit
  #"animation",         # Animation support
  #"tonemapping_luts",  # Support different camera Tonemapping modes (enables KTX2+zstd)
  "default_font",       # Embed a minimal default font for text/UI

  # File formats:
  "png",    # PNG image format for simple 2D images
  #"hdr",   # HDR images
  #"ktx2",  # Preferred format for GPU textures
  #"zstd",  # ZSTD compression support in KTX2 files
  #"vorbis",# Audio: OGG Vorbis

  # Platform-specific:
  "x11",                     # Linux: Support X11 windowing system
  "android_shared_stdcxx",   # Android: use shared C++ library
  "android-native-activity", # Android: xbuild compatibility
]
```


```
SystemInfo { os: "MacOS 15.1 ", kernel: "24.1.0", cpu: "Apple M1 Pro", core_count: "10", memory: "16.0 GiB" }
```

<img width="1728" alt="Image" src="https://github.com/user-attachments/assets/f634f8c5-6a67-4ce9-a143-7aa632ab1af4" />
