### ISSUE TITLE
without std, systems run as fast as possible

### ISSUE THREAD

**Issue by purplg** [bevyengine/bevy#18617]
## Bevy version

0.16.0-rc.2

## What you did

Executed this simple project:

### Cargo.toml
```toml
[package]
name = "bevy_timer_fast"
version = "0.1.0"
edition = "2024"

[dependencies.bevy]
version = "0.16.0-rc.2"
default-features = false
```

### main.rs
```rust
use std::time::Duration;

use bevy::app::ScheduleRunnerPlugin;
use bevy::prelude::*;
use bevy::time::common_conditions::on_timer;

fn main() {
    App::new()
        .add_plugins(
            DefaultPlugins.set(ScheduleRunnerPlugin::run_loop(Duration::from_secs_f64(
                1.0 / 60.0,
            ))),
        )
        .add_systems(Update, tick.run_if(on_timer(Duration::from_secs(1))))
        .run();
}

fn tick(time: Res<Time>) {
    println!("elapsed: {:?}", time.elapsed_secs_f64());
}
```

## What went wrong

The `elapsed_secs` seems to be increasing by ~1 second every 0.5 second and is being printed twice per second.

## Additional information

Switching to Bevy `0.15.3` does not have this problem.
