### ISSUE TITLE
Unexpected extra blank space

### ISSUE THREAD

**Issue by lomirus** [bevyengine/bevy#18764]
## Bevy version

main branch (Mar 16, 2026)

## What you did

```toml
[package]
name = "bevy-demo"
version = "0.1.0"
edition = "2024"

[dependencies.bevy]
git = "https://github.com/bevyengine/bevy.git"
rev = "24661940b42fa8c8a89538a1d3572f7fe6dbd49a" # Mar 16, 2026
default-features = false
features = [
  "bevy_log",
  "bevy_ui",
  "bevy_ui_render",
  "bevy_ui_debug",
  "bevy_winit",
  "tonemapping_luts",
  "zstd_rust",
  "default_font",
]

[profile.dev]
opt-level = 1

[profile.dev.package."*"]
opt-level = 3

[profile.release]
codegen-units = 1
lto = "fat"

```

```rust
use bevy::prelude::*;

const BAR_WIDTH: f32 = 250.0;

fn init(mut commands: Commands) {
    commands.spawn((Camera3d::default(), IsDefaultUiCamera));

    commands.spawn((
        Node {
            align_items: AlignItems::Center,
            ..default()
        },
        children![(
            Node {
                flex_direction: FlexDirection::Column,
                width: Val::Px(BAR_WIDTH),
                ..default()
            },
            BackgroundColor(Color::WHITE),
            children![
                (
                    Text::new("Jan 1, 2000 01:00"),
                    TextFont {
                        font_size: FontSize::Px(20.0),
                        ..default()
                    },
                    TextColor::from(Color::BLACK),
                ),
                (
                    Node {
                        width: Val::Px(BAR_WIDTH),
                        height: Val::Px(24.0),
                        ..default()
                    },
                    BackgroundColor(Srgba::hex("3ba6a3").unwrap().into()),
                )
            ]
        )],
    ));
}

fn toggle_debug_overlay(
    input: Res<ButtonInput<KeyCode>>,
    mut debug_options: ResMut<GlobalUiDebugOptions>,
) {
    if input.just_pressed(KeyCode::Space) {
        debug_options.toggle();
    }
}

fn main() {
    App::new()
        .add_systems(Startup, init)
        .add_systems(Update, toggle_debug_overlay)
        .add_plugins(DefaultPlugins)
        .run();
}
```

## What went wrong

You can see that there is an extra blank area below the teal bar:

![Image](https://github.com/user-attachments/assets/18f653a5-42fd-479c-90db-e0195c7fa3e6)

However, there is no extra node to support the height.

It should look like this:

![Image](https://github.com/user-attachments/assets/32d272a3-e979-476a-b7c3-1639404396f7)

## Additional information

I found that simply removing `AlignItems::Center` from the outermost `Node` fixed the issue. However, `AlignItems` shouldn't cause this behavior (and it is required in my actual game), so I believe this is likely a bug, and it's related to `AlignItems` (at least).

Result of `self.taffy.print_tree(implicit_viewport_node)`:

```
TREE
└──  GRID [x: 0    y: 0    w: 1600 h: 900  content_w: 313  content_h: 150  border: l:0 r:0 t:0 b:0, padding: l:0 r:0 t:0 b:0] (NodeId(4294967301))
    └──  FLEX ROW [x: 0    y: 0    w: 313  h: 150  content_w: 313  content_h: 150  border: l:0 r:0 t:0 b:0, padding: l:0 r:0 t:0 b:0] (NodeId(4294967298))
        └──  FLEX COL [x: 0    y: 0    w: 313  h: 150  content_w: 313  content_h: 60   border: l:0 r:0 t:0 b:0, padding: l:0 r:0 t:0 b:0] (NodeId(4294967300))
            ├──  LEAF [x: 0    y: 0    w: 313  h: 30   content_w: 256  content_h: 30   border: l:0 r:0 t:0 b:0, padding: l:0 r:0 t:0 b:0] (NodeId(4294967299))
            └──  LEAF [x: 0    y: 30   w: 313  h: 30   content_w: 0    content_h: 0    border: l:0 r:0 t:0 b:0, padding: l:0 r:0 t:0 b:0] (NodeId(4294967297))
```
