### ISSUE TITLE
`bevy_macro_utils` is handling the `bevy_ecs` path incorrectly

### ISSUE THREAD

**Issue by ManevilleF** [bevyengine/bevy#3659]
## Bevy version

Bevy 0.6

## Operating system & version

MacOS

## What you did

having this setup in `Cargo.toml`

```toml
[target.'cfg(not(target_arch = "wasm32"))'.dependencies.bevy]
version = "0.6"
default-features = false
features = ["render", "bevy_winit", "png", "dynamic", "x11"]

[target.'cfg(target_arch = "wasm32")'.dependencies.bevy]
version = "0.6"
default-features = false
features = ["render", "bevy_winit", "png"]
```

If I try to derive `bevy_ecs::Component` like this:

```rust
use bevy::prelude::Component;

#[derive(Component)]
struct MyComponent;
```

## What you expected to happen

This should work properly

## What actually happened

I get a compilation error from the  derive proc macro:

```
  |
  | #[derive(Component)]
  |          ^^^^^^^^^ use of undeclared crate or module `bevy_ecs`
  |
    = note: this error originates in the derive macro `Component`
```

## Additional information

This issue is from `bevy_macro_utils::BevyManifest::maybe_get_path` (for `bevy_ecs`) that incorrectly assumes the usage path.

A workaroud is replacing the classic usage by:

```rust
use bevy::ecs as bevy_ecs;
use bevy_ecs::prelude::Component;
```

**Comment by mockersf** [comment]
oh the macro is probably failing to catch the `bevy` dependency as they are both behind `target`...

could you add as a dependency to see if it works better:
```
bevy = { version = "0.6", default-features = false }
```

**Comment by ManevilleF** [comment]
I tried this:

```toml
[dependencies.bevy]
version = "0.6"
default-features = false

[target.'cfg(not(target_arch = "wasm32"))'.dependencies.bevy]
features = ["render", "bevy_winit", "png", "dynamic", "x11"]

[target.'cfg(target_arch = "wasm32")'.dependencies.bevy]
features = ["render", "bevy_winit", "png"]
```

and it seems to work

**Comment by bjorn3** [comment]
You could also use

```toml
[dependencies.bevy]
version = "0.6"
default-features = false
features = ["render", "bevy_winit", "png"]

[target.'cfg(not(target_arch = "wasm32"))'.dependencies.bevy]
features = ["dynamic", "x11"]
```

to avoid duplication I think.

**Comment by ManevilleF** [comment]
@bjorn3 

```toml
[dependencies.bevy]
version = "0.6"
default-features = false
features = ["render", "bevy_winit", "png"]

[target.'cfg(not(target_arch = "wasm32"))'.dependencies.bevy]
version = "0.6"
default-features = false
features = ["dynamic", "x11"]
```

This is how I ended up doing things, if the version is not specified `cargo` emits a warning, and without the second `default-features = false` every default feature is compiled
