### ISSUE TITLE
Too large WebAssembly bin file

### ISSUE THREAD

**Issue by Wandalen** [bevyengine/bevy#3800]
## What problem does this solve or what need does it fill?

Trivial example [2d_rect](https://bevyengine.org/examples/2d/rect/) weights **13MB**.

![image](https://user-images.githubusercontent.com/7414255/151672343-738655bf-fe57-4b9b-af99-1e3b6628ee51.png)

Playing with optimization option I reached ~4 MB. Still that's too much.
Is that possible to get less than 0.5 MB maybe excluding some features?

## What solution would you like?

Excluding some features?
Putting `naga` under a feature? 
More features?

**Comment by HeavyRain266** [comment]
You may want to try using this
```toml
[dependencies.bevy]
version = "0.6"
default-features = false
features = [
  "bevy_sprite",
  "bevy_render"
]
```
in your cargo manifest.

This will remove all the "bloat" from bevy and should optimize size of the binary.
