### ISSUE TITLE
#[derive(Component)] panics with unstable cargo feature `workspace-inheritance`

### ISSUE THREAD

**Issue by JK2Kgit** [bevyengine/bevy#4821]
## Bevy version

bevy = { version = ">=0.7.0", features = ["dynamic"] }

## Operating system & version

Garuda Linux (Arch Linux) updates as of 21.05.2022

## What you did

```rust
use bevy::prelude::*;

#[derive(Component)]
struct Person;


fn main() {
    App::new()
        .add_startup_system(add_people)
        .run();
}

fn add_people(mut commands: Commands) {
    commands.spawn().insert(Person);
}
```

## What you expected to happen

That It compiles and runs

## What actually happened
It panicked

```
error: proc-macro derive panicked
 --> apps/game/src/main.rs:3:10
  |
3 | #[derive(Component)]
  |          ^^^^^^^^^
  |
  = help: message: called `Result::unwrap()` on an `Err` value: Parse(Error { inner: ErrorInner { kind: Custom, line: Some(3), col: 20, at: Some(77), message: "invalid type: map, expected a string", key: ["package", "version"] } })


error[E0277]: the trait bound `Person: bevy::prelude::Component` is not satisfied
   --> apps/game/src/main.rs:13:29
    |
13  |     commands.spawn().insert(Person);
    |                      ------ ^^^^^^ the trait `bevy::prelude::Component` is not implemented for `Person`
    |                      |
    |                      required by a bound introduced by this call
    |
    = help: the following other types implement trait `bevy::prelude::Component`:
              Aabb
              AlphaMode
              AnimationPlayer
              Button
              CalculatedClip
              CalculatedSize
              Camera
              Camera2d
            and 68 others
note: required by a bound in `EntityCommands::<'w, 's, 'a>::insert`
   --> /home/<user>/.cargo/registry/src/github.com-1ecc6299db9ec823/bevy_ecs-0.7.0/src/system/commands/mod.rs:481:46
    |
481 |     pub fn insert(&mut self, component: impl Component) -> &mut Self {
    |                                              ^^^^^^^^^ required by this bound in `EntityCommands::<'w, 's, 'a>::insert`


```

## Additional information
I'm using unstable cargo feature `workspace-inheritance`

Cargo.toml
```toml
cargo-features = ["workspace-inheritance"]

[workspace]
resolver = "2"
members = [
    "libs/shared/models",
    "apps/game"
]

[workspace.dependencies]
shared_models = {path="libs/shared/models"}
bevy = { version = ">=0.7.0", features = ["dynamic"] }


[workspace.package]
version = "0.1.0"
edition = "2021"
```

apps/game/Cargo.toml
```toml
cargo-features = ["workspace-inheritance"]

[package]
version.workspace = true
edition.workspace = true
name = "game"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy.workspace = true
```

**Comment by JK2Kgit** [comment]
Works in sorry for trouble

bevy = { git="https://github.com/bevyengine/bevy.git", features = ["dynamic"], revison="fed93a0"}

**Comment by bjorn3** [comment]
The panic is probably fixed by https://github.com/bevyengine/bevy/pull/3886 which switched from full blown manifest parsing to cherry picking just those parts that are needed. Note that both before and after workspace inheritance is not fully supported. The logic only looks in the local manifest, but it would need to parse the workspace manifest too to handle package renames like

```toml
cargo-features = ["workspace-inheritance"]

[workspace]
resolver = "2"
members = [
    "libs/shared/models",
    "apps/game"
]

[workspace.dependencies]
shared_models = {path="libs/shared/models"}
my_renamed_bevy = { package = "bevy", version = ">=0.7.0", features = ["dynamic"] }


[workspace.package]
version = "0.1.0"
edition = "2021"
```

```toml
cargo-features = ["workspace-inheritance"]

[package]
version.workspace = true
edition.workspace = true
name = "game"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
my_renamed_bevy.workspace = true
```

The code would have no clue that it should use `my_renamed_bevy` when referring to bevy.
