### ISSUE TITLE
CI still runs on Rust 1.62

### ISSUE THREAD

**Issue by JoJoJet** [bevyengine/bevy#5668]
## What you did

In #5659, I made a change that relies on a fix in Rust 1.63.

## What went wrong

CI fails. It's probably still running on Rust 1.62.

**Comment by TimJentzsch** [comment]
Hmmm, I'm a bit confused by the CI action here:

<https://github.com/bevyengine/bevy/blob/de6bef72a10bda2a71c4cad0a4badf153c716f8c/.github/workflows/ci.yml#L15-L39>

Isn't this missing something like

```yaml
- uses: actions-rs/toolchain@v1
  with:
    toolchain: stable
      components: rustfmt, clippy
      override: true
```

as the other CI jobs?
Maybe it's taking the old Rust version from the cache.
