### ISSUE TITLE
Third-party plugin docs should encourage more granular dependencies

### ISSUE THREAD

**Issue by james7132** [bevyengine/bevy#6913]
## How can Bevy's documentation be improved?

The current third-party plugin guidelines suggest using `bevy` as the core dependency. This potentially introduces a heavy compile time bottleneck on the top level crate, which is exacerbated as there are some heavy dependencies in tree (i.e. `serde` and `wgpu`). This is likely to get progressively worse as the size and complexity of first party crates grows along with the ecosystem. Likewise, it also encourages plugin developers to target features on `bevy` instead of individual crates, leading to issues like #5753. To avoid this bottleneck, we should encourage plugin developers to directly depend on lower level `bevy_*` crates instead.

As @mockersf has noted [here](https://github.com/bevyengine/bevy/pull/6852#discussion_r1039063496), this does break potential discoverability via https://lib.rs/crates/bevy/rev. This is, however, potentially mitigated by encouraging plugin developers to take `bevy` on as a dev-dependency instead, for ease of use when making examples and tests.

**Comment by alice-i-cecile** [comment]
I'm on board with this strategy.

> take bevy on as a dev-dependency instead, for ease of use when making examples and tests.

This is a good compromise, and something I do for my examples and integration tests already.

**Comment by mockersf** [comment]
depending on sub crates in plugins makes patching Bevy a lot more painful

instead of
```toml
[patch.crates-io]
bevy = { git = "https://github.com/bevyengine/bevy" }
```

you end up with 
```toml
[patch.crates-io]
# still patch the global crate for your dependency as a game
bevy = { git = "https://github.com/bevyengine/bevy" }
# also patch all subcrates to patch plugins
bevy_animation = { git = "https://github.com/bevyengine/bevy" }
bevy_app = { git = "https://github.com/bevyengine/bevy" }
bevy_asset = { git = "https://github.com/bevyengine/bevy" }
bevy_audio = { git = "https://github.com/bevyengine/bevy" }
bevy_core = { git = "https://github.com/bevyengine/bevy" }
bevy_core_pipeline = { git = "https://github.com/bevyengine/bevy" }
bevy_derive = { git = "https://github.com/bevyengine/bevy" }
bevy_diagnostic = { git = "https://github.com/bevyengine/bevy" }
bevy_ecs = { git = "https://github.com/bevyengine/bevy" }
bevy_encase_derive = { git = "https://github.com/bevyengine/bevy" }
bevy_gilrs = { git = "https://github.com/bevyengine/bevy" }
bevy_gltf = { git = "https://github.com/bevyengine/bevy" }
bevy_hierarchy = { git = "https://github.com/bevyengine/bevy" }
bevy_input = { git = "https://github.com/bevyengine/bevy" }
bevy_internal = { git = "https://github.com/bevyengine/bevy" }
bevy_log = { git = "https://github.com/bevyengine/bevy" }
bevy_macro_utils = { git = "https://github.com/bevyengine/bevy" }
bevy_math = { git = "https://github.com/bevyengine/bevy" }
bevy_mikktspace = { git = "https://github.com/bevyengine/bevy" }
bevy_pbr = { git = "https://github.com/bevyengine/bevy" }
bevy_ptr = { git = "https://github.com/bevyengine/bevy" }
bevy_reflect = { git = "https://github.com/bevyengine/bevy" }
bevy_render = { git = "https://github.com/bevyengine/bevy" }
bevy_scene = { git = "https://github.com/bevyengine/bevy" }
bevy_sprite = { git = "https://github.com/bevyengine/bevy" }
bevy_tasks = { git = "https://github.com/bevyengine/bevy" }
bevy_text = { git = "https://github.com/bevyengine/bevy" }
bevy_time = { git = "https://github.com/bevyengine/bevy" }
bevy_transform = { git = "https://github.com/bevyengine/bevy" }
bevy_ui = { git = "https://github.com/bevyengine/bevy" }
bevy_utils = { git = "https://github.com/bevyengine/bevy" }
bevy_window = { git = "https://github.com/bevyengine/bevy" }
bevy_winit = { git = "https://github.com/bevyengine/bevy" }
```
