### ISSUE TITLE
Access is denied (os error 5) on occurs when compile with performance optimizations

### ISSUE THREAD

**Issue by h2cone** [bevyengine/bevy#7655]
## Bevy version

0.9.1

## Relevant system information

- Cargo version: cargo 1.67.1 (8ecd4f20a 2023-01-10)
- OS: Windows 10

## What you did

I updated my `Cargo.toml` according to [Compile with Performance Optimizations](https://bevyengine.org/learn/book/getting-started/setup/#compile-with-performance-optimizations).

```toml
[package]
name = "dinosaur"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = "0.9.1"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

# Enable a small amount of optimization in debug mode
[profile.dev]
opt-level = 1

# Enable high optimizations for dependencies (incl. Bevy), but not for our code:
[profile.dev.package."*"]
opt-level = 3
```

It works fine on MacOS, but when running `cargo run` on Windows 10, an error occurs.

## Additional information

Console output:

```shell
❯ cargo run
   Compiling windows_x86_64_msvc v0.42.1
   Compiling serde_derive v1.0.152
   Compiling thiserror-impl v1.0.38
   Compiling memchr v2.5.0
   Compiling bytemuck_derive v1.4.0
   Compiling lock_api v0.4.9
   Compiling serde v1.0.152
   Compiling pin-project-lite v0.2.9
   Compiling crossbeam-utils v0.8.14
   Compiling winapi v0.3.9
   Compiling futures-core v0.3.26
error: failed to run custom build command for `windows_x86_64_msvc v0.42.1`

Caused by:
  could not execute process `D:\vscws\dinosaur\target\debug\build\windows_x86_64_msvc-d70f02eea399ed35\build-script-build` (never executed)

Caused by:
  Access is denied. (os error 5)
warning: build failed, waiting for other jobs to finish...
```
