### ISSUE TITLE
Error with only `serialize` feature enabled

### ISSUE THREAD

**Issue by 100-TomatoJuice** [bevyengine/bevy#9787]
## Bevy version

Main

## What you did

Create a bevy project with default features off and only `serialize` enabled.
```TOML
[dependencies]
bevy = { git = "https://github.com/bevyengine/bevy.git", default-features = false, features = [
  "serialize",
] }
```
Run a Bevy app with  `DefaultPlugins`
```rust
fn main() {
    App::new()
        .add_plugins(DefaultPlugins)
        .run()
}
```

## What went wrong

The window would not be created and this error was printed to the terminal:
```
thread 'main' panicked at 'Requested resource bevy_asset::server::AssetServer does not exist in the `World`. 
```

## Additional information

This was found at https://github.com/Leafwing-Studios/leafwing-input-manager/issues/382
